marketplace/urls.py
from django.urls import path
import marketplace.views as views

app_name="marketplace"
urlpatterns = [
    path('',views.book_list_view,name='book-list'),
    path('<slug>/',views.book_detail_view,name="book-detail"),
    path('<book_slug>/<int:chapter_number>',views.chapter_detail_view,name="chapter-detail"),
    path('<book_slug>/<int:chapter_number>/<int:exercise_number>',views.exercise_detail_view,name="exercise-detail"),
]

project/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/',include('shopping_cart.urls',namespace="cart")),
    path('accounts/',include('allauth.urls')),
    path('',include('marketplace.urls'),name="marketplace"),

]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

shopping_cart/urls.py
from django.urls import path
from .views import add_to_cart,remove_from_cart,order_view,checkout

app_name = "shopping_cart"

urlpatterns = [
    path('add-to-cart/<book_slug>/',add_to_cart,name="add-to-cart"),
    path('remove-from-cart/<book_slug>/',remove_from_cart,name="remove-from-cart"),
    path('order-summary/',order_view,name="order-summary"),
    path('checkout/',checkout,name="checkout")

]

marketplace/models.py
from django.db import models
from django.shortcuts import reverse
from django.conf import settings
from django.db.models.signals import post_save
# Create your models here.
'''
Author
    Book    
        Chapter 1
            Exercise 1
                Question 1
                    Solution
                Question 2

            Exercise 2
        Chapter 2

Projects
    Resource List
    Project Components
        To Do List
        Project Components?

'''
class UserLibrary(models.Model):
    books = models.ManyToManyField("Book",blank=True)
    user = models.OneToOneField(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username
    
    def book_list(self):
        return self.books.all()

    class Meta:
        verbose_name = "User Library"
        verbose_name_plural = "User Library"

def post_user_sign_up_receiver(sender,instance,created,*args,**kwargs):
    if created:
        UserLibrary.objects.get_or_create(user=instance)

post_save.connect(post_user_sign_up_receiver,sender=settings.AUTH_USER_MODEL)

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    #slug fields are used to help create detail views
    slug = models.SlugField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

class Book(models.Model):
    authors = models.ManyToManyField(Author)
    title = models.CharField(max_length=100)
    pub_date = models.DateTimeField()
    isbn = models.CharField(max_length=16)
    slug = models.SlugField()
    cover = models.ImageField()
    price = models.FloatField()

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("marketplace:book-detail", kwargs= {
            "slug":self.slug,
        })

class Chapter(models.Model):
    book = models.ForeignKey(Book,on_delete=models.CASCADE)
    chapter_number = models.IntegerField()
    title=models.CharField(max_length=100)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("marketplace:chapter-detail", kwargs={
            "book_slug":self.book.slug,
            "chapter_number":self.chapter_number,
        })

class Exercise(models.Model):
    chapter = models.ForeignKey(Chapter,on_delete=models.CASCADE)
    exercise_number = models.IntegerField()
    page_number = models.IntegerField()
    title=models.CharField(max_length=100)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("marketplace:exercise-detail", kwargs={
            "book_slug":self.chapter.book.slug,
            "chapter_number":self.chapter.chapter_number,
            "exercise_number":self.exercise_number,
        })


class Solution(models.Model):
    exercise = models.ForeignKey(Exercise,on_delete=models.CASCADE)
    solution_number=models.IntegerField()
    image = models.ImageField()

    def __str__(self):
        return f"{self.exercise}--{self.pk}"

marketplace/views.py
from django.shortcuts import render,get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Book,Chapter,Exercise
from django.http import Http404
from shopping_cart.models import Order, OrderItem
# Create your views here.

OWNED="owned"
IN_CART="in_cart"
NOT_IN_CART="not_in_cart"


def check_book_relationship(request,book):
    if book in request.user.userlibrary.books.all():
        return OWNED
    order_qs = Order.objects.filter(user=request.user)
    if order_qs.exists():
        order = order_qs[0]
        order_item_qs = OrderItem.objects.filter(book=book)
        if order_item_qs.exists():
            order_item=order_item_qs[0]
            if order_item in order.items.all():
                return IN_CART
    return NOT_IN_CART


def book_list_view(request):
    #dislay a list of the books
    context={}
    context['queryset'] = Book.objects.all()
    return render(request,'marketplace/book_list.html',context)

@login_required
def book_detail_view(request,slug):
    # display a list of the chapter in this book
    book = get_object_or_404(Book,slug=slug)
    book_status = check_book_relationship(request,book)
    context = {
        'book':book,
        'book_status':book_status,
    }
    return render(request,'marketplace/book_detail.html',context)

@login_required
def chapter_detail_view(request,book_slug,chapter_number):
    chapter_qs = Chapter.objects.filter(book__slug=book_slug).filter(chapter_number=chapter_number)
    chapter=chapter_qs[0]
    book_status = check_book_relationship(request,chapter.book)
    if chapter_qs.exists():
        context = {
            'chapter':chapter,
            'book_status':book_status
        }
        return render(request,'marketplace/chapter_detail.html',context)
    return Http404
    
@login_required
def exercise_detail_view(request,book_slug,chapter_number,exercise_number):
    exercise_qs = Exercise.objects.filter(chapter__book__slug = book_slug).filter(chapter__chapter_number=chapter_number).filter(exercise_number=exercise_number)
    exercise=exercise_qs[0]
    book_status= check_book_relationship(request,exercise.chapter.book)
    if exercise_qs.exists():
        context = {
            'exercise':exercise,
            'book_status':book_status
        }
        return render(request,'marketplace/exercise_detail.html',context)
    return Http404

marketplace/templates/marketplace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <title>Digital Marketplace</title>
</head>
<body>
      <div class="container">

        {% include "marketplace/navbar.html" %}

        <nav aria-label="breadcrumb">
          <ol class="breadcrumb">
              {% block breadcrumb %}
          
              {% endblock breadcrumb %}
          </ol>
        </nav>
        {% block content %}

        {% endblock content %}
      </div>


    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    
</body>
</html>

marketplace/templates/marketplace/book_detail.html
{% extends 'marketplace/base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'marketplace:book-list' %}">Book List</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{book.title}}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class="row">
        <main class="col-md-4">
            {% include "marketplace/book_snippet.html" with book=book %}
        </main>
        <aside class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Chapters
                </div>
                <ul class="list-group list-group-flush">
                    {% for chapter in book.chapter_set.all %}
                        <li class="list-group-item"><a href="{{ chapter.get_absolute_url }}">{{chapter.chapter_number}}. {{chapter.title}}</a></li>
                    {% endfor %}
                </ul>
            </div>            
        </aside>
    </div>

    
    

{% endblock content%}

marketplace/templates/marketplace/book_list.html
{% extends 'marketplace/base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item active" aria-current="page">Book List</li>
{% endblock breadcrumb %}


{% block content %}

    <h1>This is the book list</h1>
    <hr />
    {% for book in queryset %}
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{book.title}}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{book.pub_date}}</h6>
                <p class="card-text">
                    {% for author in book.authors.all %}
                        <span>{{author}}</span> 
                        {% if book.authors.count > 1 %} | {% endif %}
                    {% endfor %}
                </p>
                <a href="{{ book.get_absolute_url }}" class="card-link">{{book}}</a>
            </div>
        </div>
    {% endfor %}

{% endblock content%}

marketplace/templates/marketplace/book_snippet.html
<div class="card" style="width: 18rem;">
    <div class="card-header">
        {{book.title}}
    </div>
    <img class="card-img-top" src="{{ book.cover.url }}" alt="Card image cap">
    <div class="card-body">
        <p class="card-text">{{book.pub_date}}</p>
    </div>
    {% if book_status != 'owned' %}
        {% if book_status == 'in_cart' %}
            <div class="card-footer">
                <a class="btn btn-default btn-block" href="{% url 'cart:remove-from-cart' book.slug %}">Remove from cart</a>
            </div>
        {% else %}
            <div class="card-footer">
                <a class="btn btn-warning btn-block" href="{% url 'cart:add-to-cart' book.slug %}">Add to cart</a>
            </div>
        {% endif %}
    {% endif %}
    
</div>        

marketplace/templates/marketplace/chapter_detail.html
{% extends 'marketplace/base.html' %}

{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'marketplace:book-list' %}">Book List</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{ chapter.book.get_absolute_url }}" >{{chapter.book.title}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{chapter}}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class="row">
        <main class="col-md-4">
            {% include "marketplace/book_snippet.html" with book=chapter.book %}      
        </main>

        <aside class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Exercises
                </div>
                <ul class="list-group list-group-flush">
                    {% for exercise in chapter.exercise_set.all  %}
                        <li class="list-group-item"><a href="{{ exercise.get_absolute_url }}">{{exercise.exercise_number}}. {{exercise}}</a></li>
                    {% endfor %}
                </ul>
            </div>            
        </aside>
    </div>
{% endblock content%}

marketplace/templates/marketplace/checkout.html
{% extends 'marketplace/base.html' %}

{% load static %}

{% block content %}

    <link href="{% static 'shopping_cart/css/stripe_form.css' %}" rel="stylesheet" />
    <script src="https://js.stripe.com/v3/"></script>
    <h1>Checkout</h1>
    <hr />

     
    <p>Order Total: ${{ order.get_total }}</p>
    <form action="." method="post" id="payment-form">
        {% csrf_token %}
        <div class="stripe-form-row">
            <label for="card-element">
            Credit or debit card
            </label>
            <div id="card-element" class="StripeElement">
            <!-- A Stripe Element will be inserted here. -->
            </div>

            <!-- Used to display form errors. -->
            <div id="card-errors" role="alert"></div>
        </div>

        <button class="btn btn-primary">Submit Payment</button>
    </form>    
      

<script src="{% static 'shopping_cart/js/stripe_form.js' %}"></script>
    

{% endblock content%}

marketplace/templates/marketplace/exercise_detail.html
{% extends 'marketplace/base.html' %}
{% load static %}


{% block breadcrumb %}
    <li class="breadcrumb-item" aria-current="page"><a href="{% url 'marketplace:book-list' %}">Book List</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{exercise.chapter.book.get_absolute_url}}" >{{exercise.chapter.book.title}}</a></li>
    <li class="breadcrumb-item" aria-current="page"><a href="{{exercise.chapter.get_absolute_url}}">{{exercise.chapter}}</a></li>
    <li class="breadcrumb-item active" aria-current="page">{{exercise}}</li>
{% endblock breadcrumb %}


{% block content %}
    <div class="row">
        <main class="col-md-4">
            {% include "marketplace/book_snippet.html" with book=exercise.chapter.book %}   
        </main>

        <aside class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Solutions
                </div>

                {% if exercise.chapter.book in request.user.userlibrary.book_list %}

                {% for solution in exercise.solution_set.all %}
                    <div id="toggle-{{solution.solution_number}}">
                        <div class="card">
                            <div class="card-header" id="heading-{{solution.solution_number}}">
                                <h5 class="mb-0">
                                    <button class="btn btn-link" data-toggle="collapse" data-target="#collapse-{{solution.solution_number}}" aria-expanded="true" aria-controls="collapse-{{solution.solution_number}}">
                                        Solution {{solution.solution_number}}
                                    </button>
                                </h5>
                            </div>
                        </div>

                        <div id="collapse-{{solution.solution_number}}" class="collapse" aria-labelledby="heading-{{solution.solution_number}}" data-parent="#toggle-{{solution.solution_number}}">
                            <div class="card-image">
                                <img src="{{ solution.image.url }}" />
                            </div>
                        </div>                       
                    </div>
                {% endfor %}

                {% else %}
                <div class="text-center">
                    <h4>You do not have access to this book. <a href="#">Purchase this book</a> to have access to this solution.</h4>
                    <img src="{% static 'images/lock.jpeg' %}"/>
                </div>
                {% endif %}

            </div>            
        </aside>
    </div>
{% endblock content%}

marketplace/templates/marketplace/navbar.html
{% load cart_template_tags %}

<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <a class="navbar-brand" href="{% url "marketplace:book-list" %}">Marketplace</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09" aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarsExample09">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url "marketplace:book-list" %}">Home</a>
        </li>
        {% if request.user.is_authenticated %}
            <li class="nav-item">
            <a class="nav-link" href="{% url 'account_logout' %}">Logout</a>
            </li>
            <li class="nav-item">
            <a class="nav-link" href="{% url 'cart:order-summary' %}">{{ request.user|cart_item_count }}</a>
            </li>
        {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_login' %}">Login</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
            </li>
        {% endif %}
        
        
      </ul>
      <form class="form-inline my-2 my-md-0">
        <input class="form-control" type="text" placeholder="Search" aria-label="Search">
      </form>
    </div>
</nav>

marketplace/templates/marketplace/order_summary.html
{% extends 'marketplace/base.html' %}

{% block content %}

    <h1>Order Summary</h1>
    <hr />

    <table class="table table-hover table-bordered text-center">
        <tr class="text-center">
            <th>no.</th>
            <th>Title</th>
            <th>Price</th>
        </tr>
        {% for item in order.items.all %}
        <tr>
            <td>{{ forloop.counter }}</td>
            <td>{{item.book.title}}<span class="text-danger"><a href="{% url 'cart:remove-from-cart' item.book.slug %}"> Delete Item</a></span></td>
            <td>${{item.book.price}}</td>
            
        </tr>
        {% empty %}
        <tr>
            <td colspan="3"> 
                There are no items in your cart
            </td>
        </tr>
        {% endfor %}
        {% if order.get_total %}
        <tr>
            <td colspan="2">
                <strong class="pull-right"> Order Total</strong>
            </td>
            <td colspan="1">
                <strong class="pull-right"> ${{order.get_total}} </strong>
            </td>
        </tr>
        {% endif %}

        <tr>
            <td colspan="3">
                <a href="{% url 'marketplace:book-list' %}"class="btn btn-warning pull-left">
                {% if order %}
                    Continue shopping
                {% else %}
                    Add items to your cart
                {% endif %}
                </a>
            </td>
        </tr>

        {% if order.get_total %}
        <tr>
            <td colspan="3">
                <a href="{% url 'cart:checkout' %}"class="btn btn-primary pull-left">
                    Check Out
                </a>
            </td>
        </tr>
        {% endif %}

    </table>
    
    

{% endblock content%}